### Numpy 
 - it is a general purpose array processing package.
 - it provides high performance multidimensional array object and tool for making with these array.
 - it is the fundamental package for scientific computing with python.

### Array
  - Data Structure that stores values of same datatypes.

In [7]:
#importing  numpy
import numpy as np

In [9]:
my_lst =[1,2,3,4,5]

In [13]:
arr = np.array(my_lst)

In [15]:
arr

array([1, 2, 3, 4, 5])

In [17]:
type(arr)

numpy.ndarray

In [19]:
arr.shape

(5,)

In [30]:
# Multidimensional Array

In [32]:
my_lst1 = [1,2,3,4,5]

In [34]:
my_lst2 = [6,7,8,9,10]

In [36]:
my_lst3 = [11,12,13,14,15]

In [38]:
arr = np.array([my_lst1 , my_lst2, my_lst3])

In [40]:
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [42]:
arr.shape

(3, 5)

In [50]:
lst = arr.reshape(5,3)

In [52]:
lst

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15]])

In [54]:
lst.shape

(5, 3)

##### Indexing in Numpy Array

In [59]:
# Accessing the Array Elements

In [61]:
arr = np.array([1,2,3,4,5,6,7,8,9,0])

In [63]:
arr[3]

4

In [67]:
arr1 = np.array([[1,2,3,4,5] , [6,7,8,9,10] ,[11,12,13,14,15]])

In [69]:
arr1

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [71]:
arr1[: , :]

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [73]:
arr1[0:2,0:2]

array([[1, 2],
       [6, 7]])

In [75]:
arr1[1: ,3: ]

array([[ 9, 10],
       [14, 15]])

In [77]:
arr1[1: ,2:4]

array([[ 8,  9],
       [13, 14]])

In [79]:
arr2 = np.array([[1,2,3,4,5] , [2,3,4,5,6] , [9,7,6,8,9]])

In [81]:
arr2

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 6],
       [9, 7, 6, 8, 9]])

In [83]:
arr2[1: ,3: ]

array([[5, 6],
       [8, 9]])

In [85]:
arr2[1: ,2:4]

array([[4, 5],
       [6, 8]])

In [91]:
arr2[1:2,1:4]

array([[3, 4, 5]])

In [93]:
# Arange Function

In [97]:
arr = np.arange(0,10)

In [99]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [101]:
arr = np.arange(0,15,step =2)

In [103]:
arr

array([ 0,  2,  4,  6,  8, 10, 12, 14])

In [107]:
# linspace 
# Syntax np.linspace([start , stop, num==no ])

In [111]:
np.linspace(1,10,50)

array([ 1.        ,  1.18367347,  1.36734694,  1.55102041,  1.73469388,
        1.91836735,  2.10204082,  2.28571429,  2.46938776,  2.65306122,
        2.83673469,  3.02040816,  3.20408163,  3.3877551 ,  3.57142857,
        3.75510204,  3.93877551,  4.12244898,  4.30612245,  4.48979592,
        4.67346939,  4.85714286,  5.04081633,  5.2244898 ,  5.40816327,
        5.59183673,  5.7755102 ,  5.95918367,  6.14285714,  6.32653061,
        6.51020408,  6.69387755,  6.87755102,  7.06122449,  7.24489796,
        7.42857143,  7.6122449 ,  7.79591837,  7.97959184,  8.16326531,
        8.34693878,  8.53061224,  8.71428571,  8.89795918,  9.08163265,
        9.26530612,  9.44897959,  9.63265306,  9.81632653, 10.        ])

In [113]:
# Copy function & Broad Casting

In [117]:
arr = np.arange(0,10)

In [119]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [123]:
arr[3:] = 100

In [125]:
arr

array([  0,   1,   2, 100, 100, 100, 100, 100, 100, 100])

In [127]:
arr1 = arr

In [129]:
arr1

array([  0,   1,   2, 100, 100, 100, 100, 100, 100, 100])

In [131]:
arr1[3: ] = 500

In [135]:
arr1

array([  0,   1,   2, 500, 500, 500, 500, 500, 500, 500])

In [137]:
arr1 = arr.copy()

In [139]:
arr1

array([  0,   1,   2, 500, 500, 500, 500, 500, 500, 500])

In [141]:
arr

array([  0,   1,   2, 500, 500, 500, 500, 500, 500, 500])

In [143]:
print(arr)

[  0   1   2 500 500 500 500 500 500 500]


In [145]:
arr1[3: ] =1000

In [147]:
print(arr1)

[   0    1    2 1000 1000 1000 1000 1000 1000 1000]


In [149]:
arr

array([  0,   1,   2, 500, 500, 500, 500, 500, 500, 500])

In [151]:
# Conditions useful in Exploratory Data Analysis

In [153]:
arr<2

array([ True,  True, False, False, False, False, False, False, False,
       False])

In [155]:
arr[arr<2]

array([0, 1])

In [157]:
arr*2

array([   0,    2,    4, 1000, 1000, 1000, 1000, 1000, 1000, 1000])

In [159]:
arr

array([  0,   1,   2, 500, 500, 500, 500, 500, 500, 500])

In [161]:
arr%2

array([0, 1, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int32)

In [163]:
arr%3

array([0, 1, 2, 2, 2, 2, 2, 2, 2, 2], dtype=int32)

In [165]:
arr/2

array([  0. ,   0.5,   1. , 250. , 250. , 250. , 250. , 250. , 250. ,
       250. ])

In [167]:
arr**2

array([     0,      1,      4, 250000, 250000, 250000, 250000, 250000,
       250000, 250000])

In [169]:
# Creating Array & Reshape

In [171]:
np.arange(0,10).reshape(5,2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [173]:
arr1 = np.arange(0,10).reshape(2,5)

In [181]:
arr1

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [175]:
arr2 = np.arange(0,10).reshape(2,5)

In [179]:
arr2

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [177]:
arr1*arr2

array([[ 0,  1,  4,  9, 16],
       [25, 36, 49, 64, 81]])

In [183]:
# .ones -- elements replace by 1's
# Syntax -- np.ones(shape, dtype = none)

In [185]:
np.ones(4)

array([1., 1., 1., 1.])

In [187]:
np.ones(4, dtype = int)

array([1, 1, 1, 1])

In [191]:
np.ones((2,5), dtype = float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [193]:
# Random Distribution -- It takes between 0 to 1

In [195]:
np.random.rand(3,3)

array([[0.7127313 , 0.07155202, 0.72821807],
       [0.36472251, 0.39476196, 0.35645242],
       [0.60865624, 0.41483884, 0.03897905]])

In [197]:
np.random.rand(4,5)

array([[0.5374423 , 0.91535556, 0.16497964, 0.48797453, 0.87977632],
       [0.79254228, 0.15447878, 0.88663581, 0.3850435 , 0.75084403],
       [0.06009345, 0.88933874, 0.31513777, 0.33878479, 0.86830361],
       [0.79328032, 0.58398028, 0.85640218, 0.98167496, 0.59152296]])

In [199]:
#randn

In [201]:
arr_ex = np.random.randn(4,4)

In [203]:
arr_ex

array([[-1.06625814,  0.10188687,  1.12408085, -0.21311226],
       [ 0.34262634, -1.09661787,  0.17263175, -0.05198193],
       [-1.51369374, -0.17453259,  0.12997   ,  0.44564571],
       [-0.51452774,  1.01204537, -0.53119939,  1.0864551 ]])

In [205]:
# randint

In [207]:
np.random.randint(0,100,8).reshape(4,2)

array([[80, 60],
       [15, 24],
       [58, 77],
       [75, 31]])

In [209]:
np.random.randint(0,1250,8)

array([325, 622, 955,   1, 893, 983, 403, 249])

In [211]:
# random_sample

In [217]:
np.random.random_sample((1,15))

array([[0.8716009 , 0.81195312, 0.43239427, 0.41031421, 0.5992427 ,
        0.79629935, 0.03893224, 0.18071183, 0.51984421, 0.43819002,
        0.17084122, 0.72112563, 0.80154863, 0.12099282, 0.97314955]])